# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genmedia < Formula
  desc "AI media generation CLI powered by fal.ai"
  homepage "https://github.com/ilkerzg/genmedia"
  version "0.1.2-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ilkerzg/genmedia/releases/download/v0.1.2-beta/genmedia_darwin_amd64.tar.gz"
      sha256 "1ca5b8f908dbab28cd2225402978664dcc131751267cb564158255204fbd9e43"

      define_method(:install) do
        bin.install "genmedia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ilkerzg/genmedia/releases/download/v0.1.2-beta/genmedia_darwin_arm64.tar.gz"
      sha256 "9d4060f17e88d6326b2fa7bc8c3cc6efcb54fb90c43cb741135ea13443d219ca"

      define_method(:install) do
        bin.install "genmedia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilkerzg/genmedia/releases/download/v0.1.2-beta/genmedia_linux_amd64.tar.gz"
      sha256 "4ac0cca274ece0c45ff70ceebb742f07e434e0d9c99b6dfb2dad9b6b2d7fce2d"
      define_method(:install) do
        bin.install "genmedia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilkerzg/genmedia/releases/download/v0.1.2-beta/genmedia_linux_arm64.tar.gz"
      sha256 "432b3a50a6c1ca696f4c06a511c00273a8f2e64ca59ed04694513197d7e39785"
      define_method(:install) do
        bin.install "genmedia"
      end
    end
  end
end
