# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genmedia < Formula
  desc "AI media generation CLI powered by fal.ai"
  homepage "https://github.com/ilkerzg/genmedia"
  version "0.1.0-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ilkerzg/genmedia/releases/download/v0.1.0-beta/genmedia_darwin_amd64.tar.gz"
      sha256 "b290dbb343ee27fb3960caafb8558df9586751992366f80994962875c752fdf4"

      define_method(:install) do
        bin.install "genmedia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ilkerzg/genmedia/releases/download/v0.1.0-beta/genmedia_darwin_arm64.tar.gz"
      sha256 "56a27e415b213dd189620d9750cd4bb9254b11d764d1d9e3277aaa8b75b41fa6"

      define_method(:install) do
        bin.install "genmedia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilkerzg/genmedia/releases/download/v0.1.0-beta/genmedia_linux_amd64.tar.gz"
      sha256 "b4861f5afa8cf4465e09bfc29f2f2ef9563c0436ecc6d323a360a72d3b2b8af3"
      define_method(:install) do
        bin.install "genmedia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ilkerzg/genmedia/releases/download/v0.1.0-beta/genmedia_linux_arm64.tar.gz"
      sha256 "b262fe725aa27433a96473d1f7e878eed3b63720fc40aa7942d09d28188b0ed3"
      define_method(:install) do
        bin.install "genmedia"
      end
    end
  end
end
